### ISSUE TITLE
Webpack compilation error

### ISSUE THREAD

**Issue by wawyed** [elaichenkov/cy-verify-downloads#61]
When running with Typescript + Cypress 10

```
Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'path' in '/Users/xxxx/WebstormProjects/canopy-angular/node_modules/cy-verify-downloads/src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

Module not found: Error: Can't resolve 'fs' in '/Users/xxxx/WebstormProjects/canopy-angular/node_modules/cy-verify-downloads/src'

Module not found: Error: Can't resolve 'crypto' in '/Users/xxxx/WebstormProjects/canopy-angular/node_modules/cy-verify-downloads/src'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
    at Watching.handle [as handler] (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Watching.js:290:9
    at Hook.eval [as callAsync] (eval at create (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Watching.js:287:28)
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Watching.js:209:21
    at Compiler.emitRecords (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Compiler.js:919:5)
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Watching.js:187:22
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Compiler.js:882:27
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/neo-async/async.js:2818:7
    at done (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxxx/WebstormProjects/canopy-angular/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/webpack/lib/Compiler.js:736:33
    at /Users/xxxx/WebstormProjects/canopy-angular/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/xxxx/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/xxxx/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/xxxx/Library/Caches/Cypress/10.3.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
```

**Comment by elaichenkov** [comment]
Hey,
This issue is not related to the package at all. Please, set up your compiler and config correctly. Also, don't forget to add all `node.js` polyfills. As an example:
https://github.com/elaichenkov/cy-verify-downloads/issues/51#issuecomment-1237978973

If it doesn't help you, then feel free to create a repository with the reproducible code. I'll take a look at it.

**Comment by wawyed** [comment]
Fixed by adding to my webpackconfig:

```      webpackOptions: {
        plugins: [new NodePolyfillPlugin()],
        resolve: {
          extensions: ['.ts', '.js'],
          fallback: {
            fs: require.resolve('browserify-fs'),
          }```
